In [2]:
library(tidyverse)
library(ggplot2)
library(haven)
library(stargazer)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

In [3]:
df <- read_dta("data/cen_ind_2021_pumf_v2.dta")
head(df)

  ppsort aboid agegrp ageimm attsch bfnmemb bedrm CFInc CFInc_AT cfstat ⋯
1 1      6     13      7     1      0       4     30    27       2      ⋯
2 2      6     11      5     1      0       3     18    18       2      ⋯
3 3      1     13     99     1      0       0      7     7       6      ⋯
4 4      6     16     99     1      0       4     15    15       2      ⋯
5 5      6     18     99     1      0       3     13    13       3      ⋯
6 6      2     16     99     1      0       4      1     1       7      ⋯
  WT7      WT8      WT9      WT10      WT11     WT12     WT13     WT14
1 22.90113 22.90113 22.90113 249.27876 22.90113 22.90113 22.90113  22.90113
2 22.89379 22.89379 22.89379  22.89379 22.89379 22.89379 22.89379  22.89379
3 22.90134 22.90134 22.90134  22.90134 22.90134 22.90134 22.90134  22.90134
4 22.87713 22.87713 22.87713  22.87713 22.87713 22.87713 22.87713  22.87713
5 22.90134 22.90134 22.90134  22.90134 22.90134 22.90134 22.90134  22.90134
6 22.89284 22.89284 22.89284  22.89284 22.89284 22.89284 22.89284 249.18847
  WT15     WT16
1 22.90113 22.90113
2 22.89379 22.89379
3 22.90134 22.90134
4 22.87713 22.87713
5 22.90134 22.90134
6 22.89284 22.89284

In [4]:
names(df)

  [1] "ppsort"           "aboid"            "agegrp"
  [4] "ageimm"           "attsch"           "bfnmemb"
  [7] "bedrm"            "CFInc"            "CFInc_AT"
 [10] "cfstat"           "chdbn"            "CIP2021"
 [13] "CIP2021_STEM_SUM" "cma"              "condo"
 [16] "COVID_ERB"        "cow"              "cqppb"
 [19] "CapGn"            "CfSize"           "ChldC"
 [22] "CitOth"           "Citizen"          "dist"
 [25] "dpgrsum"          "dtype"            "EFDecile"
 [28] "EFInc"            "EFInc_AT"         "eicbn"
 [31] "ethder"           "EfDIMBM_2018"     "EfSize"
 [34] "EmpIn"            "fol"              "fptwk"
 [37] "Gender"           "genstat"          "GovtI"
 [40] "GTRfs"            "HCORENEED_IND"    "hdgree"
 [43] "HHInc"            "HHInc_AT"         "hhmrkinc"
 [46] "hhsize"           "hhtype"           "hlmosten"
 [49] "hlmostfr"         "hlmostno"         "hlregen"
 [52] "hlregfr"          "hlregno"          "IMMCAT5"
 [55] "immstat"          "IncTax"           "Invst"
 [58] "jobperm"          "kol"              "lfact"
 [61] "LICO_BT"          "LICO_AT"          "liprogtype"
 [64] "LI_ELIG_OML_U18"  "locstud"          "LOC_ST_RES"
 [67] "lstwrk"           "lwmosten"         "lwmostfr"
 [70] "lwmostno"         "lwregen"          "lwregfr"
 [73] "lwregno"          "LoLIMA"           "LoLIMB"
 [76] "LOMBM_2018"       "mode"             "MTNEn"
 [79] "MTNFr"            "mtnno"            "marsth"
 [82] "Mob1"             "Mob5"             "MrkInc"
 [85] "naics"            "NOC21"            "nol"
 [88] "nos"              "oasgi"            "OtInc"
 [91] "PKID25"           "PKID0_1"          "PKID15_24"
 [94] "PKID2_5"          "PKID6_14"         "pkids"
 [97] "pob"              "POBPAR1"          "POBPAR2"
[100] "powst"            "pr"               "PR1"
[103] "PR5"              "presmortg"        "prihm"
[106] "pwdur"            "pwleave"          "pwocc"
[109] "pwpr"             "regind"           "relig"
[112] "repair"           "room"             "Retir"
[115] "shelco"           "ssgrad"           "subsidy"
[118] "SempI"            "tenur"            "TotInc"
[121] "TotInc_AT"        "vismin"           "Value"
[124] "wkswrk"           "wrkact"           "Wages"
[127] "yrim"             "weight"           "WT1"
[130] "WT2"              "WT3"              "WT4"
[133] "WT5"              "WT6"              "WT7"
[136] "WT8"              "WT9"              "WT10"
[139] "WT11"             "WT12"             "WT13"
[142] "WT14"             "WT15"             "WT16"

In [5]:
selected_df <- df|>
    select(lfact, agegrp, immstat, ageimm, yrim, hdgree, Gender, marsth, vismin) 
head(selected_df)

  lfact agegrp immstat ageimm yrim hdgree Gender marsth vismin
1 88    13     88       7     2008 7      2      2      88
2  3    11      2       5     2005 7      1      2       2
3 14    13      1      99     9999 2      1      1       1
4 13    16      1      99     9999 5      2      2      88
5 13    18      1      99     9999 2      2      5       1
6 13    16      1      99     9999 2      1      6       1

In [6]:
summary(selected_df)

     lfact           agegrp         immstat           ageimm          yrim
 Min.   : 1.00   Min.   : 1.00   Min.   : 1.000   Min.   : 1.0   Min.   :   1
 1st Qu.: 1.00   1st Qu.: 8.00   1st Qu.: 1.000   1st Qu.:99.0   1st Qu.:9999
 Median : 6.00   Median :12.00   Median : 1.000   Median :99.0   Median :9999
 Mean   :21.21   Mean   :11.69   Mean   : 1.401   Mean   :77.5   Mean   :7999
 3rd Qu.:13.00   3rd Qu.:16.00   3rd Qu.: 2.000   3rd Qu.:99.0   3rd Qu.:9999
 Max.   :99.00   Max.   :88.00   Max.   :88.000   Max.   :99.0   Max.   :9999
     hdgree          Gender          marsth          vismin
 Min.   : 1.00   Min.   :1.000   Min.   :1.000   Min.   : 1.00
 1st Qu.: 2.00   1st Qu.:1.000   1st Qu.:1.000   1st Qu.: 1.00
 Median : 6.00   Median :1.000   Median :2.000   Median : 1.00
 Mean   :20.77   Mean   :1.494   Mean   :2.062   Mean   : 4.23
 3rd Qu.: 9.00   3rd Qu.:2.000   3rd Qu.:2.000   3rd Qu.: 2.00
 Max.   :99.00   Max.   :2.000   Max.   :8.000   Max.   :88.00

In [7]:
filtered_df <- selected_df|>
    filter(lfact < 14) |>
    filter(between(agegrp, 16, 17)) |>
    filter(immstat < 3) |> #Remove non-permanent residents and not available
    filter(ageimm != 88) |> #keep 99 here since that's canadian born
    filter(yrim != 8888) |> #keep 9999 here since that's canadian born
    filter(vismin != 88) |>

    mutate(eligible = if_else(immstat == 1 | (immstat == 2 & yrim <= 2011), 1, 0)) |>
    mutate(NILF = if_else(lfact >= 11, 1, 0)) |>
    mutate(agegrp = if_else(agegrp == 16, 0, 1)) |> #Change age group to dummy, 0 if 16, 1 if 17
    mutate(women = if_else(Gender == 1, 1, 0)) |>
    mutate(vismin_dummy = if_else(vismin > 1, 1, 0)) |>

    #categorical variables
    filter(hdgree != 88 & hdgree != 99) |> 
    mutate(educ_level = case_when(
        hdgree == 1 ~ "1_Less_Than_HS",
        hdgree == 2 ~ "2_High_School",
        hdgree >= 3 & hdgree <= 8 ~ "3_College_Trades",
        hdgree >= 9 & hdgree <= 13 ~ "4_University",
        TRUE ~ NA_character_
    )) |> 
    mutate(educ_level = as.factor(educ_level)) |>

    filter(marsth != 8) |> 
    mutate(marital_group = case_when(
        marsth %in% c(2, 3) ~ "1_Partnered",         # Code 2 (Married), Code 3 (Common law)
        marsth %in% c(4, 5, 6) ~ "2_Prev_Married",   # Code 4 (Separated), 5 (Divorced), 6 (Widowed)
        marsth == 1 ~ "3_Never_Married",                    # Code 1 (Never married)
        TRUE ~ NA_character_
    )) |>
    mutate(marital_group = as.factor(marital_group)) |>

    select(NILF, eligible, agegrp, women, vismin_dummy, educ_level, marital_group)

head(filtered_df)

  NILF eligible agegrp women vismin_dummy educ_level       marital_group
1 1    1        0      1     0            2_High_School    2_Prev_Married
2 1    1        0      1     0            4_University     1_Partnered
3 1    1        0      0     0            3_College_Trades 1_Partnered
4 0    1        1      1     0            3_College_Trades 1_Partnered
5 1    1        1      0     0            4_University     1_Partnered
6 0    1        0      0     0            2_High_School    1_Partnered

In [8]:
summary(filtered_df)

      NILF           eligible          agegrp           women
 Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.000
 1st Qu.:0.0000   1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:0.000
 Median :1.0000   Median :1.0000   Median :0.0000   Median :1.000
 Mean   :0.5404   Mean   :0.9868   Mean   :0.4545   Mean   :0.509
 3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.000
 Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.000
  vismin_dummy               educ_level            marital_group
 Min.   :0.0000   1_Less_Than_HS  :17112   1_Partnered    :82187
 1st Qu.:0.0000   2_High_School   :34320   2_Prev_Married :22460
 Median :0.0000   3_College_Trades:39172   3_Never_Married:10449
 Mean   :0.1446   4_University    :24492
 3rd Qu.:0.0000
 Max.   :1.0000

before running regressions, it is worth checking if the treatment group

In [36]:
t.test(vismin_dummy ~ eligible, data = filtered_df)

	Welch Two Sample t-test

data:  vismin_dummy by eligible
t = 68.464, df = 1550.1, p-value < 2.2e-16
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.6625458 0.7016293
sample estimates:
mean in group 0 mean in group 1
      0.8176432       0.1355556

In [37]:
base_reg <- lm(NILF ~ eligible, data = filtered_df)
summary(base_reg)

Call:
lm(formula = NILF ~ eligible, data = filtered_df)

Residuals:
    Min      1Q  Median      3Q     Max
-0.5406 -0.5406  0.4594  0.4594  0.4740

Coefficients:
            Estimate Std. Error t value Pr(>|t|)
(Intercept)  0.52600    0.01279  41.136   <2e-16 ***
eligible     0.01462    0.01287   1.136    0.256
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4984 on 115094 degrees of freedom
Multiple R-squared:  1.122e-05,	Adjusted R-squared:  2.527e-06
F-statistic: 1.291 on 1 and 115094 DF,  p-value: 0.2559

In [41]:
stargazer(base_reg, type = "text")

===============================================
                        Dependent variable:
                    ---------------------------
                               NILF
-----------------------------------------------
eligible                       0.015
                              (0.013)

Constant                     0.526***
                              (0.013)

-----------------------------------------------
Observations                  115,096
R2                            0.00001
Adjusted R2                   0.00000
Residual Std. Error     0.498 (df = 115094)
F Statistic           1.291 (df = 1; 115094)
===============================================
Note:               *p<0.1; **p<0.05; ***p<0.01

In [47]:
full_reg <- lm(NILF ~ eligible + agegrp ++ women + educ_level + marital_group + vismin_dummy, data = filtered_df)
summary(full_reg)

Call:
lm(formula = NILF ~ eligible + agegrp + +women + educ_level +
    marital_group + vismin_dummy, data = filtered_df)

Residuals:
    Min      1Q  Median      3Q     Max
-0.8735 -0.4319  0.2319  0.4027  0.7728

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                  0.461252   0.013137  35.110  < 2e-16 ***
eligible                    -0.037550   0.012533  -2.996  0.00273 **
agegrp                       0.279948   0.002806  99.756  < 2e-16 ***
women                        0.114592   0.002819  40.656  < 2e-16 ***
educ_level2_High_School     -0.050119   0.004447 -11.269  < 2e-16 ***
educ_level3_College_Trades  -0.068254   0.004351 -15.686  < 2e-16 ***
educ_level4_University      -0.106391   0.004731 -22.487  < 2e-16 ***
marital_group2_Prev_Married -0.010001   0.003600  -2.778  0.00547 **
marital_group3_Single        0.055296   0.004924  11.229  < 2e-16 ***
vismin_dummy                -0.080077   0.004092 -19.570  < 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.473 on 115086 degrees of freedom
Multiple R-squared:  0.09942,	Adjusted R-squared:  0.09935
F-statistic:  1412 on 9 and 115086 DF,  p-value: < 2.2e-16

In [43]:
did_cov <- lm(NILF ~ eligible + agegrp + eligible * agegrp, data = filtered_df)

summary(did_cov)

Call:
lm(formula = NILF ~ eligible + agegrp + eligible * agegrp, data = filtered_df)

Residuals:
    Min      1Q  Median      3Q     Max
-0.6935 -0.4133  0.3065  0.3065  0.5867

Coefficients:
                 Estimate Std. Error t value Pr(>|t|)
(Intercept)      0.418519   0.016814  24.891   <2e-16 ***
eligible        -0.005181   0.016923  -0.306    0.759
agegrp           0.230283   0.024611   9.357   <2e-16 ***
eligible:agegrp  0.049894   0.024775   2.014    0.044 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4785 on 115092 degrees of freedom
Multiple R-squared:  0.07803,	Adjusted R-squared:  0.07801
F-statistic:  3247 on 3 and 115092 DF,  p-value: < 2.2e-16

In [44]:
stargazer(did_cov, type = "text", title = "DiD Baseline No Controls")

DiD Baseline No Controls
=================================================
                         Dependent variable:
                    -----------------------------
                                NILF
-------------------------------------------------
eligible                       -0.005
                               (0.017)

agegrp                        0.230***
                               (0.025)

eligible:agegrp                0.050**
                               (0.025)

Constant                      0.419***
                               (0.017)

-------------------------------------------------
Observations                   115,096
R2                              0.078
Adjusted R2                     0.078
Residual Std. Error      0.479 (df = 115092)
F Statistic         3,247.108*** (df = 3; 115092)
=================================================
Note:                 *p<0.1; **p<0.05; ***p<0.01

In [45]:
did_cov_ctrl <- lm(NILF ~ eligible + agegrp + eligible * agegrp + women + educ_level + marital_group + vismin_dummy, data = filtered_df)

summary(did_cov_ctrl)

Call:
lm(formula = NILF ~ eligible + agegrp + eligible * agegrp + women +
    educ_level + marital_group + vismin_dummy, data = filtered_df)

Residuals:
    Min      1Q  Median      3Q     Max
-0.8740 -0.4315  0.2315  0.4024  0.7731

Coefficients:
                             Estimate Std. Error t value Pr(>|t|)
(Intercept)                  0.485116   0.017304  28.034  < 2e-16 ***
eligible                    -0.061714   0.016945  -3.642 0.000271 ***
agegrp                       0.228752   0.024325   9.404  < 2e-16 ***
women                        0.114593   0.002819  40.657  < 2e-16 ***
educ_level2_High_School     -0.050131   0.004447 -11.272  < 2e-16 ***
educ_level3_College_Trades  -0.068282   0.004351 -15.692  < 2e-16 ***
educ_level4_University      -0.106469   0.004731 -22.503  < 2e-16 ***
marital_group2_Prev_Married -0.009998   0.003600  -2.777 0.005486 **
marital_group3_Single        0.055340   0.004924  11.238  < 2e-16 ***
vismin_dummy                -0.080001   0.004092 -19.551  < 2e-16 ***
eligible:agegrp              0.051886   0.024489   2.119 0.034110 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.473 on 115085 degrees of freedom
Multiple R-squared:  0.09945,	Adjusted R-squared:  0.09937
F-statistic:  1271 on 10 and 115085 DF,  p-value: < 2.2e-16

In [46]:
stargazer(did_cov_ctrl, type = "text", title = "DiD with Controls")

DiD with Controls
==========================================================
                                 Dependent variable:
                            ------------------------------
                                         NILF
----------------------------------------------------------
eligible                              -0.062***
                                       (0.017)

agegrp                                 0.229***
                                       (0.024)

women                                  0.115***
                                       (0.003)

educ_level2_High_School               -0.050***
                                       (0.004)

educ_level3_College_Trades            -0.068***
                                       (0.004)

educ_level4_University                -0.106***
                                       (0.005)

marital_group2_Prev_Married           -0.010***
                                       (0.004)

marital_group3_Single                  0.055***
                                       (0.005)

vismin_dummy                          -0.080***
                                       (0.004)

eligible:agegrp                        0.052**
                                       (0.024)

Constant                               0.485***
                                       (0.017)

----------------------------------------------------------
Observations                           115,096
R2                                      0.099
Adjusted R2                             0.099
Residual Std. Error              0.473 (df = 115085)
F Statistic                 1,270.958*** (df = 10; 115085)
==========================================================
Note:                          *p<0.1; **p<0.05; ***p<0.01

In [80]:
install.packages("webshot2")
library(webshot2)

stargazer(
    base_reg, full_reg, did_cov, did_cov_ctrl,
    type = "text", #changed the type here
    title = "Cross-sectional DD-style models",
    dep.var.labels = "Not in labour force (NILF)",
    column.labels = c("Baseline", "Controls", "DiD", "DiD + controls"),
    covariate.labels = c(
        "Eligible (OAS)",
        "Age 65-69",
        "Female",
        "High school (ref: < HS)",
        "College/Trades (ref: < HS)",
        "University (ref: < HS)",
        "Previously married (ref: partnered)",
        "Never Married (ref: partnered)",
        "Visible minority",
        "Eligible x Age 65-69"),
    digits = 3,
    out = "dd_style_table_full.txt" #file created
)

webshot("dd_style_table_full.txt", "dd_style_table_full.png",vwidth = 1200, vheight = 800)

Cross-sectional DD-style models
=====================================================================================================================================================
                                                                                   Dependent variable:
                                    -----------------------------------------------------------------------------------------------------------------
                                                                               Not in labour force (NILF)
                                           Baseline                  Controls                         DiD                      DiD + controls
                                             (1)                        (2)                           (3)                           (4)
-----------------------------------------------------------------------------------------------------------------------------------------------------
Eligible (OAS)                              0.015                    -0.038***                      -0.005                       -0.062***
                                           (0.013)                    (0.013)                       (0.017)                       (0.017)

Age 65-69                                                            0.280***                      0.230***                       0.229***
                                                                      (0.003)                       (0.025)                       (0.024)

Female                                                               0.115***                                                     0.115***
                                                                      (0.003)                                                     (0.003)

High school (ref: < HS)                                              -0.050***                                                   -0.050***
                                                                      (0.004)                                                     (0.004)

College/Trades (ref: < HS)                                           -0.068***                                                   -0.068***
                                                                      (0.004)                                                     (0.004)

University (ref: < HS)                                               -0.106***                                                   -0.106***
                                                                      (0.005)                                                     (0.005)

Previously married (ref: partnered)                                  -0.010***                                                   -0.010***
                                                                      (0.004)                                                     (0.004)

Never Married (ref: partnered)                                       0.055***                                                     0.055***
                                                                      (0.005)                                                     (0.005)

Visible minority                                                     -0.080***                                                   -0.080***
                                                                      (0.004)                                                     (0.004)

Eligible x Age 65-69                                                                                0.050**                       0.052**
                                                                                                    (0.025)                       (0.024)

Constant                                   0.526***                  0.461***                      0.419***                       0.485***
                                           (0.013)                    (0.013)                       (0.017)                       (0.017)

-----------------------------------------------------------------------------------------------------------------------------------------------------
Observations                               115,096                    115,096                       115,096                       115,096
R2                                         0.00001                     0.099                         0.078                         0.099
Adjusted R2                                0.00000                     0.099                         0.078                         0.099
Residual Std. Error                  0.498 (df = 115094)        0.473 (df = 115086)           0.479 (df = 115092)           0.473 (df = 115085)
F Statistic                         1.291 (df = 1; 115094) 1,411.634*** (df = 9; 115086) 3,247.108*** (df = 3; 115092) 1,270.958*** (df = 10; 115085)
=====================================================================================================================================================
Note:                                                                                                                     *p<0.1; **p<0.05; ***p<0.01

file:///C:/Users/utaha/OneDrive/Desktop/Econ 398/Project/dd_style_table_full.txt screenshot completed

In [71]:

# Html
stargazer(
    base_reg, full_reg, did_cov, did_cov_ctrl,
    type = "text", #changed the type here
    title = "Cross-sectional DD-style models",
    dep.var.labels = "Not in labour force (nilf)",
    column.labels = c("Baseline", "Controls", "DiD", "DiD + controls"),
    covariate.labels = c("Eligible", "Age 65 or older", "Eligible x Age 65 or older"), 
    keep = c("^eligible$", "^agegrp$", "^eligible:agegrp$"),
    digits = 3)

Cross-sectional DD-style models
============================================================================================================================================
                                                                          Dependent variable:
                           -----------------------------------------------------------------------------------------------------------------
                                                                      Not in labour force (nilf)
                                  Baseline                  Controls                         DiD                      DiD + controls
                                    (1)                        (2)                           (3)                           (4)
--------------------------------------------------------------------------------------------------------------------------------------------
Eligible                           0.015                    -0.038***                      -0.005                       -0.062***
                                  (0.013)                    (0.013)                       (0.017)                       (0.017)

Age 65 or older                                             0.280***                      0.230***                       0.229***
                                                             (0.003)                       (0.025)                       (0.024)

Eligible x Age 65 or older                                                                 0.050**                       0.052**
                                                                                           (0.025)                       (0.024)

--------------------------------------------------------------------------------------------------------------------------------------------
Observations                      115,096                    115,096                       115,096                       115,096
R2                                0.00001                     0.099                         0.078                         0.099
Adjusted R2                       0.00000                     0.099                         0.078                         0.099
Residual Std. Error         0.498 (df = 115094)        0.473 (df = 115086)           0.479 (df = 115092)           0.473 (df = 115085)
F Statistic                1.291 (df = 1; 115094) 1,411.634*** (df = 9; 115086) 3,247.108*** (df = 3; 115092) 1,270.958*** (df = 10; 115085)
============================================================================================================================================
Note:                                                                                                            *p<0.1; **p<0.05; ***p<0.01